export default [
  {
    id: 1,
    img: "/products/product1.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["lipsticks"],
    sale: true,
  },
  {
    id: 2,
    img: "/products/product2.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["lipsticks"],
    sale: true,
  },

  {
    id: 3,
    img: "/products/product4.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["lipsticks", "makeup"],
    sale: true,
  },
  {
    id: 4,
    img: "/products/product5.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["skin care"],
    sale: true,
  },
  {
    id: 5,
    img: "/products/product6.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 6,
    img: "/products/product7.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["nail & wax"],
    sale: true,
  },
  {
    id: 7,
    img: "/products/product8.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["nail & wax"],
    sale: true,
  },
  {
    id: 8,
    img: "/products/product9.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["nail & wax"],
    sale: false,
  },
  {
    id: 9,
    img: "/products/product10.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["nail & Wax"],
    sale: false,
  },
  {
    id: 10,
    img: "/products/product11.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["makeup"],
    sale: true,
  },
  {
    id: 11,
    img: "/products/product12.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["skin care"],
    sale: true,
  },
  {
    id: 12,
    img: "/products/product13.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["makeup", "nail & wax"],
    sale: true,
  },
  {
    id: 13,
    img: "/products/product14.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["makeup", "nail & wax"],
    sale: true,
  },
  {
    id: 14,
    img: "/products/product15.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["makeup", "nail & wax"],
    sale: false,
  },
  {
    id: 15,
    img: "/products/product16.png",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["makeup", "nail & wax"],
    sale: false,
  },
];
